version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 19
    commands:
      - echo Entered the install phase...
      - java -version
      - gradle -v
  build:
    commands:
      - gradle build -x test

artifacts:
  files:
    - ./build/libs/exercise-manage-backend.jar