spring:
  profiles: production
  jpa:
    show-sql: true
  datasource:
    initialization-mode: always
    url: jdbc:mysql://exercise-manage-app-db-2.cyhjaivb7n6v.ap-northeast-1.rds.amazonaws.com:3306
    username: root
    password:
conf:
  path:
    images: src/main/resources/static/upload/
  url:
    host: http://localhost:8080