server:
  tomcat:
    accesslog:
      enabled: true
  port: 8080
spring:
  batch:
    initialize-schema: always
    job:
      enabled: false
  profiles:
    active: local
  messages:
    basename: i18n/messages_ja
    cache-duration: 1
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 3000KB
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

