server:
  port: 80
spring:
  profiles: production
  jpa:
    show-sql: true
  datasource:
    initialization-mode: always
    url: jdbc:mysql://10.0.40.10:3306/exercise_manage
    username: root
    password: adminAdmin9!
conf:
  path:
    images: src/main/resources/static/upload/
  url:
    host: http://localhost:8080